services:
  - type: web
    name: ludus-gestao-api
    env: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000 