version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ludus_gestao_postgres
    environment:
      POSTGRES_DB: ludusdb_dev
      POSTGRES_USER: ludus
      POSTGRES_PASSWORD: ludus123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ludus-network
    restart: unless-stopped

  # API Application
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ludus_gestao_api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ludusdb_dev;Username=ludus;Password=ludus123
    volumes:
      - ../:/src
      - /src/bin
      - /src/obj
    depends_on:
      - postgres
    networks:
      - ludus-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ludus-network:
    driver: bridge
