version: '3.8'

services:
  # API Application
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ludus_gestao_api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # A connection string será lida do appsettings.json
    networks:
      - ludus-network
    restart: unless-stopped

networks:
  ludus-network:
    driver: bridge
